config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  get '/pending_appointments', to: 'appointments#pending_appointments'
  get '/accepted_appointments', to: 'appointments#accepted_appointments'


  root 'home#index'

  devise_for :users, skip: [:registrations, :sessions], :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :"new_user_session"
    post 'login', to: 'users/sessions#create', as: :"user_session"
    delete 'logout', to: 'users/sessions#destroy', as: :"destroy_user_session"
    get 'create_user', to: 'users/registrations#new', as: :"new_user_registration"
    post 'create_user', to: 'users/registrations#create', as: :"user_registration"
    post 'create_user_as_admin', to: 'users/registrations#create_as_admin', as: :"admin_registration"
    delete '', to: 'users/registrations#destroy', as: :""
    patch 'users/:id', to: 'users/registrations#update', as: :"update_user_registration"
    put 'users/:id', to: 'users/registrations#update', as: :""
    get 'users/:id/edit', to: 'users/registrations#edit', as: :"edit_user_registration"

  end

  resources :rooms
  resources :appointments
  get 'my-appointments' => 'appointments#my_appointments'
  get 'all-appointments' => 'appointments#all_appointments'
  get 'backoffice', to: 'backoffice/dashboard#index'
  get 'signup_user', to: 'backoffice/dashboard#signup_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
# Classe que declara uma sala disponível para aluguel
# cadastrada com os dados "nome", "capacidade" e "local"
class Room < ApplicationRecord
	has_many :appointments
	has_many :users, :through => :appointments
	validates :name, presence: true, length: {minimum: 3, maximum: 50}
	validates :location, presence: true, length: {minimum: 3, maximum: 50}
	validates :students, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :signed_in?
	before_action :is_admin?, only: [:new, :create, :destroy]
	skip_before_action :verify_authenticity_token
	def new
		@room = Room.new
	end

	def index
		@rooms = Room.all
	end

	def show
		@room = Room.find(params[:id])
	end

	def edit
		@room = Room.find(params[:id])
	end

	def update
		@room = Room.find(params[:id])
		if @room.update(room_params)
			redirect_to @room
			flash[:notice] = "A sala foi editada com sucesso!"
		else
			flash[:danger] = "A sala não pôde ser editada! Tente novamente!"
			render 'edit'
		end
	end

	def create
		@room = Room.new(room_params)
		if @room.save
			flash[:notice] = "A sala foi criada com sucesso!"
			redirect_to backoffice_path
		else
			flash[:danger] = "A sala não pôde ser criada!"
			redirect_to backoffice_path
		end
	end

	def destroy
		@room = Room.find(params[:id])
		@room.destroy
		flash[:danger] = "A sala foi excluída"
		redirect_to backoffice_path
	end


	private

	def signed_in?
		if current_user
			true
		else
			flash[:danger] = "Você não pode acessar essa página"
			return redirect_to '/'
		end
  	end

	def is_admin?
		if current_user.is_admin
			true
		else
			flash[:danger] = "Você não pode acessar essa página"
			return redirect_to '/'
		end
	end

	##
	# GET /rooms/new
	# Parâmetros permitidos para a criação dos campos nome, local e capacidade da sala
	# POST /rooms
	# Assim como para renderizar na view do usuário, e assim um usuário não administrador
	# poder ver a capacidade máxima da sala
	def room_params
		params.require(:room).permit(:name, :location, :students)
	end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/rooms_helper.rb
# coding: utf-8

##
# Módulo com funções auxiliares para manipular salas.
module RoomsHelper
  ##
  # Retorna uma string personalizada para cada caso da status. Retornos:
  # * status == 1 : "Aguardando confirmação"
  # * status == 2 : "Confirmada"
  # * status == 3 : "Rejeitada"
  # * outros : "A invalid status identifier (status)"  
  def get_status_string(status)
    if status.to_i == 1
      return "Aguardando confirmação"
    elsif status.to_i == 2
      return "Confirmada"
    elsif status.to_i == 3
      return "Rejeitada"
    else raise "invalid status identifier " + status.to_i.to_s
    end
  end
end

app/views/rooms/edit.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<h2>Edit Room</h2>

<%= form_for(@room) do |r| %>
  
  <div class="field">
    <%= r.label :name %><br>
    <%= r.text_area :name, autofocus: true, autocomplete: "Name" %>
  </div>

  <div class="field">
    <%= r.label :location %><br>
    <%= r.text_area :location, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= r.label :tipo_sala %><br>
    <%= r.select :tipo_sala, options_for_select([['Auditórios', "Auditórios"], ['Laboratórios', "Laboratórios"], ['Multiuso', "Multiuso"], ['Salas de Aula', "Salas de Aula"], ['Salas de Reunião', "Salas de Reunião"]]), {:include_blank => "Selecione o tipo de sala"}, { :class => 'custom-select' } %>
  </div>
  
  <div class="actions">
    <%= r.submit "Update" %>
  </div>

<% end %>

app/views/rooms/filtro.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<h1 class="luc">Listagem de salas</h1>

<div class="dropluc">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">                                         
      <div class="dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Tipos de Sala
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/rooms">Todas as Salas</a>
          <a class="dropdown-item" href="/filtro/Auditórios">Auditórios</a>
          <a class="dropdown-item" href="/filtro/Laboratórios">Laboratórios</a>
          <a class="dropdown-item" href="/filtro/Multiuso">Multiuso</a>
          <a class="dropdown-item" href="/filtro/Salas de Aula">Salas de Aula</a>
          <a class="dropdown-item" href="/filtro/Salas de Reunião">Salas de Reunião</a>
        </div>
      </div>
    </div>
  </body>
</div>


<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Location</th>
    <th scope="col">Categoria</th>
    <td scope="col">Actions</td>
  </tr>
  </thead>
  <tbody>
  <% @rooms.each do |room| %>
    <% if params[:id] == room.tipo_sala%>
      <div class="room-item">
          <tr>
            <td><%= room.name %></td>
            <td><%= room.location %></td>
            <td><%= room.tipo_sala %></td>
            <td>
              <%= link_to 'Show', room_path(room.id) %>
              <%= link_to 'Aluguel', appointment_path(room.id) %>
              <% if current_user.is_admin? %>
                <%= link_to 'Edit', edit_room_path(room.id) %>
                <%= link_to 'Deletar', room_path(room), method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            </td>
          </tr>
      </div>
    <% end %>
  <% end %>
  </tbody>
</table>
<% if current_user.is_admin? %>
  <%= link_to "Backoffice", backoffice_path, class: 'btn btn-secondary' %>
  <%= link_to "Create room", new_room_path, class: 'btn btn-success' %>
<% else %>
  <%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>
<% end %>

app/views/rooms/index.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<h1>Listagem de salas</h1>
<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Location</th>
    <th scope="col">Capacidade de alunos</th>
    <td scope="col">Actions</td>
  </tr>
  </thead>
  <tbody>
  <% @rooms.each do |room| %>
    <div class="room-item">
      <tr>
        <td><%= room.name %></td>
        <td><%= room.location %></td>
        <td><%= room.students %></td>
        <td>
          <%= link_to 'Show', room_path(room.id) %>
          <%= link_to 'Aluguel', appointment_path(room.id) %>
          <% if current_user.is_admin? %>
            <%= link_to 'Edit', edit_room_path(room.id) %>
            <%= link_to 'Deletar', room_path(room), method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </td>
      </tr>
    </div>
  <% end %>
  </tbody>
</table>
<% if current_user.is_admin? %>
  <%= link_to "Backoffice", backoffice_path, class: 'btn btn-secondary' %>
  <%= link_to "Create room", new_room_path, class: 'btn btn-success' %>
<% else %>
  <%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>
<% end %>
<%==pagy_bootstrap_nav(@pagy)%>

app/views/rooms/new.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<div class="row">
  <div class="col-xs-12 col-md-12">
    <%= form_for @room, :url => {:action => "create"}, :method => "post"  do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-12">
          <%= f.label 'Nome' %>
        </div>
        <div class="col-sm-12">
          <%= f.text_field :name, class: "	form-control", placeholder: "Nome da sala", autofocus: 	true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-12">
          <%= f.label 'Capacidade maxima' %>
        </div>
        <div class="col-md-12" type="number">
          <%= f.text_field :students, type:"number", class:"form-control",placeholder: "Capacidade maxima", autofocus:true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label 'Localização' %> <br>
        </div>
        <div class="col-sm-12 col-md-12">
          <%= f.text_area :location, class: "form-control", rows: 3, placeholder: "Localização da sala" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Criar Sala", class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/search_result.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<h1>Resultado da busca de Salas Disponíveis</h1>
<div>
    <span>Data: <%= params[:date_search]%> Horário: <%= params[:time_search]%></span>
</div>

<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Location</th>
    <td scope="col">Actions</td>
  </tr>
  </thead>
  <tbody>
  <% @search_result.each do |room| %>
    <div class="room-item">
      <tr>
        <td><%= room.name %></td>
        <td><%= room.location %></td>
        <td>
          <%= link_to 'Show', room_path(room.id) %>
          <%= link_to 'Aluguel', appointment_path(room.id) %>
        </td>
      </tr>
    </div>
  <% end %>
  </tbody>
</table>

<%= link_to "Voltar a Busca", search_rooms_path, class:'btn btn-secondary' %>

app/views/rooms/search_rooms.html.erb
<%= content_for :css do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<h1>Busca de Salas Disponíveis</h1>

<%= form_tag search_result_path do %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label>Data a buscar</label>
      <%= date_field_tag :date_search, class: 'form-control'  %>
    </div>
    <div class="form-group col-md-6">
      <label>Horário</label>
      <%= select_tag :time_search, options_for_select([['6:00 - 8:00', "6:00"], ['8:00 - 10:00', "8:00"], ['10:00 - 12:00', "10:00"],['12:00 - 14:00', "12:00"], ['14:00 - 16:00', "14:00"], ['16:00 - 18:00', "16:00"], ['18:00 - 20:00', "18:00"], ['20:00 - 22:00', "20:00"],['22:00 - 24:00', "22:00"]]) %>
    </div>
    <div class="form-group col-md-6">
      <%= submit_tag "Buscar"%>
    </div>
  </div>
<% end %>

app/views/rooms/show.html.erb
<h1>Painel de visualização de Sala</h1>
<div>
    <span><%= @room.name%> : <%= @room.location%> : <%= @room.students%></span>
</div>