config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  get '/pending_appointments', to: 'appointments#pending_appointments'
  get '/accepted_appointments', to: 'appointments#accepted_appointments'


  root 'home#index'

  devise_for :users, skip: [:registrations, :sessions], :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :"new_user_session"
    post 'login', to: 'users/sessions#create', as: :"user_session"
    delete 'logout', to: 'users/sessions#destroy', as: :"destroy_user_session"
    get 'create_user', to: 'users/registrations#new', as: :"new_user_registration"
    post 'create_user', to: 'users/registrations#create', as: :"user_registration"
    post 'create_user_as_admin', to: 'users/registrations#create_as_admin', as: :"admin_registration"
    delete '', to: 'users/registrations#destroy', as: :""
    patch 'users/:id', to: 'users/registrations#update', as: :"update_user_registration"
    put 'users/:id', to: 'users/registrations#update', as: :""
    get 'users/:id/edit', to: 'users/registrations#edit', as: :"edit_user_registration"

  end

  resources :rooms
  resources :appointments
  get 'my-appointments' => 'appointments#my_appointments'
  get 'all-appointments' => 'appointments#all_appointments'
  get 'backoffice', to: 'backoffice/dashboard#index'
  get 'signup_user', to: 'backoffice/dashboard#signup_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/dashboard_controller.rb
##
# Class responsável por armazenar todos os métodos relacionados a dashboard do admin
class Backoffice::DashboardController < BackofficeController
	helper 'backoffice/dashboard'

	# Controller que lista todas as informações necessárias para a dashboard do admin
	# Assim ele é responsável por informar o número de usuários, salas, pedidos de reserva totais, pedidos de reserva de salas pendentes e horários reservados para o dia atual do sistema
	def index
		##
		# Variável de instância @rooms, @users, @todays_appointments recebe todas as salas contidas no banco de dados do sistema
		@todays_appointments = Appointment.todays_appointments
		@users = User.where(is_admin: false)
		@rooms = Room.all
		@pending_appointments = Appointment.where(status: 1).count
		@accepted_appointments = Appointment.where(status: 2).count
	end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	layout 'backoffice'
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def resource_class
		User
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/dashboard/index.html.erb
<div class="content-wrapper">

  <div class="container-fluid">
		<h1 class='text-center pb-5 pt-5'>BackOffice</h1>

		<div class="col-xs-10 col-xs-offset-5">
			<% flash.each do |name, msg| %>
				<div class='alert alert-<%="#{name}"%>'>
					<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				</div>
				<% end %>
		</div>

		

		<% if user_signed_in? %>
			<% if current_user.is_admin? %>
				<div>Signed in as... <%= current_user.email %></div>
				<%= link_to 'Adicionar Sala', new_room_path, method: :get, class: 'btn btn-primary' %>
				<%= link_to 'Ver lista de salas existentes', rooms_path, method: :get, class: 'btn btn-primary' %>
				<%= link_to 'Cadastrar um novo usuário', signup_user_path, class: 'btn btn-primary' %>
				<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>

				
				
			<% end %>
		<% end %>

		<section class="pb-4 d-flex w-100 justify-content-between">
			<div class="card align-items-center justify-content-center" style="width: 18rem;">
				<div class="card-body">
					<h5 class="card-title text-center">Nº de Usuários</h5>
					<h1 class="card-text text-center"><%= @users.count %></h1>
					<a href="users/show" class="btn btn-primary d-flex text-center">
						<h6 class="w-100 m-0">Ver usuários</h6>
					</a>
				</div>
			</div>

			<div class="card align-items-center justify-content-center" style="width: 18rem;">
				<div class="card-body">
					<h5 class="card-title text-center">Nº de Salas</h5>
					<h1 class="card-text text-center"><%= @rooms.count %></h1>
					<a href="rooms" class="btn btn-primary d-flex text-center">
						<h6 class="w-100 m-0">Ver Salas</h6>
					</a>
				</div>
			</div>

			<div class="card align-items-center justify-content-center" style="width: 18rem;">
				<div class="card-body">
					<h5 class="card-title text-center">Nº Pedidos Pendentes</h5>
					<h1 class="card-text text-center"><%= @pending_appointments %></h1>
					<a href="pending_appointments" class="btn btn-primary d-flex text-center">
						<h6 class="w-100 m-0">Ver Pendentes</h6>
					</a>
				</div>
			</div>

			<div class="card align-items-center justify-content-center" style="width: 18rem;">
				<div class="card-body">
					<h5 class="card-title text-center">Nº Reservas Confirmadas</h5>
					<h1 class="card-text text-center"><%= @accepted_appointments %></h1>
					<a href="accepted_appointments" class="btn btn-primary d-flex text-center">
						<h6 class="w-100 m-0">Ver Confirmadas</h6>
					</a>
				</div>
			</div>
		</section>

		<h1>Horários de Hoje </h1>
				<% if @todays_appointments.length > 0 %>				
					<% @todays_appointments.each do |appointment| %>						
						<%= link_to ("#{appointment[:time]} na #{appointment[:room_name]}"), edit_appointment_path(appointment[:id]) %>
						<br>						
					<% end %>
				<% else %>
					<p>Não há horários reservados para hoje.</p>
				<% end %>
	</div>
</div>

app/views/backoffice/dashboard/new.html.erb
<h2>Sign up (FOR ADMIN)</h2>

<%= form_for(resource, as: resource_name, url:  registration_path(resource)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :registration %><br />
    <%= f.text_field :registration, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "users/shared/links" %>

app/views/backoffice/dashboard/signup_user.html.erb
<div class="content-wrapper">
  <div class="container-fluid">
		<h1 class='text-center'>Cadastrar novo usuário</h1>
		<div class="col-xs-10 col-xs-offset-5">
      <%= form_for(:user ,:html => {class: "form-horizontal ogin100-form validate-form", role: "form"}, url: admin_registration_path, method: :post) do |f| %>
        <%= devise_error_messages! %>
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <div class="row">
          <div class="col-sm-12">
            <div class="field form-group">
              <%= f.label :username, class: "form-control-label" %><br />
              <%= f.text_field :username, autofocus: true, autocomplete: "off", class: "form-control", required: true %>
            </div>
          </div>

          <div class="col-sm-12 col-md-4">
              <div class="field form-group">
                <%= f.label "Matrícula", class: "form-control-label" %><br />
                <%= f.text_field :registration, autocomplete: "off", class: "form-control", required: true %>
              </div>
          </div>

          <div class="col-sm-12 col-md-8">
            <div class="field form-group">
              <%= f.label "Curso", class: "form-control-label" %><br />
              <%= f.text_field :course, autocomplete: "off", class: "form-control" %>
            </div>
          </div>

          <div class="col-sm-12">
            <div class="field form-group">
              <%= f.label :email, class: "form-control-label" %><br />
              <%= f.email_field :email, autocomplete: "email", class: "form-control", required: true  %>
            </div>
          </div>

          <div class="col-sm-12 col-md-6">
            <div class="field form-group">
              <%= f.label "Senha", class: "form-control-label" %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", class: "form-control", required: true  %>
            </div>
          </div>

          <div class="col-sm-12 col-md-6">
            <div class="field form-group">
              <%= f.label "Confirmação de senha", class: "form-control-label" %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", required: true  %>
            </div>
          </div>

          <div class="col-sm-12">
            <div class="field form-group">
              <%= f.label "É ADMIN?", class: "form-control-label" %><br />
              <%= f.check_box :is_admin  %>
            </div>
          </div>

          <div class="col-sm-12">
            <div class="actions">
              <%= f.submit "Cadastrar", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "users/shared/links" %>