config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  get '/pending_appointments', to: 'appointments#pending_appointments'
  get '/accepted_appointments', to: 'appointments#accepted_appointments'


  root 'home#index'

  devise_for :users, skip: [:registrations, :sessions], :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :"new_user_session"
    post 'login', to: 'users/sessions#create', as: :"user_session"
    delete 'logout', to: 'users/sessions#destroy', as: :"destroy_user_session"
    get 'create_user', to: 'users/registrations#new', as: :"new_user_registration"
    post 'create_user', to: 'users/registrations#create', as: :"user_registration"
    post 'create_user_as_admin', to: 'users/registrations#create_as_admin', as: :"admin_registration"
    delete '', to: 'users/registrations#destroy', as: :""
    patch 'users/:id', to: 'users/registrations#update', as: :"update_user_registration"
    put 'users/:id', to: 'users/registrations#update', as: :""
    get 'users/:id/edit', to: 'users/registrations#edit', as: :"edit_user_registration"

  end

  resources :rooms
  resources :appointments
  get 'my-appointments' => 'appointments#my_appointments'
  get 'all-appointments' => 'appointments#all_appointments'
  get 'backoffice', to: 'backoffice/dashboard#index'
  get 'signup_user', to: 'backoffice/dashboard#signup_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
# Classe que registra o aluguel de uma sala,
# que pode ser feito por um usuário ou administrador,
# informando obrigatoriamente a data e horário do aluguel
class Appointment < ApplicationRecord
  belongs_to :room
  belongs_to :user
  validates_presence_of :start_time
  validates_presence_of :appointment_date

  # Retorna uma lista dos agendamentos de hoje.
  def self.todays_appointments
    appointment_date = Time.new(Date.today.year, Date.today.month, Date.today.day, 0, 0, 0, "+00:00")
    todays_appointments = []
    appointments_for_today = Appointment.where(appointment_date: appointment_date)

		# Nas linhas abaixo vou deixar o horário mais bonito, no padrão HH:MM
		appointments_for_today.each do |appointment|
			clean_time = appointment.start_time.strftime("%H:%M")
			todays_appointments << {room_name: Room.find(appointment.room_id).name, time: clean_time, id: appointment.id}
		end

    return todays_appointments
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @room = Room.find(params[:id])
  end

  ##
  # POST /appointments
  # registra o aluguel de uma sala, feito pelo usuário autenticado e
  # contendo obrigatoriamente a data e horário do aluguel.
  # O motivo (description) é opcional.
  def create
    room_id = params[:format]
    @appointment = Appointment.new
    @appointment.room_id = params[:format]
    @appointment.user_id = current_user.id
    @appointment.appointment_date = params[:appointment_date]
    @appointment.start_time = params[:start_time]
    @appointment.description = params[:description]
    @appointment.status = 1
    if (params[:appointment_date].size > 0) and (params[:start_time].size > 0) and @appointment.save
      redirect_to backoffice_path
      flash[:notice] = "Alguel realizado com sucesso!"
    else
      redirect_to backoffice_path
      flash[:danger] = "Algo deu errado!"
    end
  end

  def show
    @room = Room.find(params[:id])
    @appointments = Appointment.where('appointment_date >= ? AND room_id = ?', Date.today.beginning_of_week, params[:id]).all
    @dates = (Date.today.beginning_of_week..Date.today.beginning_of_week+6).map{ |date| date.strftime("%a (%d/%b)") }
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to all_appointments_path
      flash.now[:notice] = "O aluguél foi editado com sucesso!"
    else
      flash.now[:danger] = "O aluguél não pôde ser editado! Tente novamente!"
      render 'edit'
    end
  end

  def my_appointments
    @user = current_user
    @my_appointments = @user.appointments
  end

  def all_appointments
    @appointments = Appointment.all
  end

  def pending_appointments
    @appointments = Appointment.where(status: 1)
  end

  def accepted_appointments
    @appointments = Appointment.where(status: 2)
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    flash[:danger] = "O Aluguel foi cancelado com suceso"
    redirect_to root_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:status)
  end
end

app/views/appointments/accepted_appointments.html.erb
<h1>Pedidos Aprovados </h1>
<table class="table" id="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Usuário</th>
    <th scope="col">Sala</th>
    <th scope="col">Data do aluguel</th>
    <th scope="col">Início</th>
    <th scope="col">Descrição</th>

    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @appointments.each do |appointment| %>
    <tr>
      <th scope="row">1</th>
      <td class="appointment-data"> <%= appointment.user.username %> </td>
      <td class="appointment-data"> <%= appointment.room.name %> </td>
      <td class="appointment-data"> <%= appointment.appointment_date %> </td>
      <td class="appointment-data"> <%= appointment.start_time %> </td>
      <td> <%= link_to 'Editar', edit_appointment_path(appointment.id) %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>

app/views/appointments/all_appointments.html.erb
<h1>Todos os pedidos </h1>
<table class="table" id="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Usuário</th>
    <th scope="col">Sala</th>
    <th scope="col">Data do aluguel</th>
    <th scope="col">Início</th>
    <th scope="col">Descrição</th>

    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @appointments.each do |appointment| %>
    <tr>
      <th scope="row">1</th>
      <td class="appointment-data"> <%= appointment.user.username %> </td>
      <td class="appointment-data"> <%= appointment.room.name %> </td>
      <td class="appointment-data"> <%= appointment.appointment_date %> </td>
      <td class="appointment-data"> <%= appointment.start_time %> </td>
      <td> <%= link_to 'Editar', edit_appointment_path(appointment.id) %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>

app/views/appointments/conflicting_appointments.html.erb
<table class="table" id="table">
  <thead>
    <h1>Conflitos</h1>
  </thead>
  <tbody>
  <% if @exists%>
    <% @conflicts.each do |conflict| %>
      <% if conflict.size > 1 %>
      <tr>
        <th scope="col">Sala: <%= conflict[0].room.name%></th>
        <th scope="col">Appointment Date: <%= conflict[0].appointment_date%></th>
        <th scope="col">Start Time: <%= conflict[0].start_time%></th>
        <th scope="col"></th>
      </tr>
        <% conflict.each do |appointment| %>
        <tr>
          <th scope="appointment-data">ID> <%= appointment.id %></th>
          <td class="appointment-data">Username> <%= appointment.user.username %> </td>
          <td class="appointment-data">Status> <%= appointment.status %> </td>
          <td> <%= link_to 'Editar', edit_appointment_path(appointment.id) %> </td>
        </tr>
        <% end %>
      <% end %>
    <% end %>
  <%else%>
    <th scope="col">Não existem conflitos.</th>
  <%end%>
  </tbody>
</table>
<%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %> <%= link_to "Voltar às reservas", '/all-appointments', class:'btn btn-secondary' %>

app/views/appointments/edit.html.erb
<h2>Edit Appointment</h2>

<%= form_for(@appointment) do |r| %>
  
  <div class="field">
    <%= r.label :status %><br>
    <%= r.select :status, [['Solicitado', '1'], ['Aprovado', '2'], ['Reprovado', '3']] %>
  </div>
  
  
  <div class="actions">
    <%= r.submit "Update" %>
  </div>

<% end %>

app/views/appointments/my_appointments.html.erb
<table class="table" id="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Appointment Date</th>
    <th scope="col">Start Time</th>
    <th scope="col">Status</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @my_appointments.each do |appointment| %>
    <tr>
      <th scope="row">1</th>
      <td class="appointment-data"> <%= appointment.appointment_date %> </td>
      <td class="appointment-data"> <%= appointment.start_time %> </td>
      <td class="appointment-data"> <%= get_status_string(appointment.status) %> </td>
      <td> <%= link_to "Cancelar Aluguel", appointment_path(appointment), method: :delete %> </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>

app/views/appointments/pending_appointments.html.erb
<h1>Pedidos Pendentes </h1>

<table class="table" id="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Usuário</th>
    <th scope="col">Sala</th>
    <th scope="col">Data do aluguel</th>
    <th scope="col">Início</th>
    <th scope="col">Descrição</th>

    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @appointments.each do |appointment| %>
    <tr>
      <th scope="row">1</th>
      <td class="appointment-data"> <%= appointment.user.username %> </td>
      <td class="appointment-data"> <%= appointment.room.name %> </td>
      <td class="appointment-data"> <%= appointment.appointment_date %> </td>
      <td class="appointment-data"> <%= appointment.start_time %> </td>
      <td> <%= link_to 'Editar', edit_appointment_path(appointment.id) %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>

app/views/appointments/show.html.erb
<h2>Name: <%=@room.name %></h2>
<h3>Location: <%=@room.location %></h3>
<p><%= @room.name%> : <%= @room.location%></p>

<br>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
    <tr class="text-center">
      <th scope="col">Horários/Dias</th>
      <% @dates.each do |date| %>
        <th scope="col"><%= date.strftime("%a (%d/%b)") %></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% i=0 %>
    <% start_t = 6 %>
    <% end_t = 8 %>
    <% while i < 9 do %>
      <tr>
        <td class="text-center align-middle"><%= start_t %>-<%= end_t %></td>
        <% @dates.each do |date| %>
          <% found = false %>
          <% @appointments.each do |appointment| %>
            <% app = appointment.start_time.hour.minutes.to_i  %>
            <% if appointment.appointment_date == date and app >= Time.parse("0#{start_t.to_s}:00").hour.minutes.to_i and app < Time.parse("0#{end_t.to_s}:00").hour.minutes.to_i %>
              <td class="text-center align-middle">
                  <button type="button" class="btn btn-danger disabled" title="<%= "#{start_t}_#{date}" %>">    
                      <% if appointment.status == 1 %>
                        Indisponível
                      <% elsif appointment.status == 2 %>
                        Aprovado
                      <% else %>
                        Reprovado
                      <% end %>
                  </button>
              </td>
              <% found = true %>
            <% end %>
          <% end %>
          <% if found == false %>
            <td class="text-center align-middle" style="color: green">
              <button type="button" class="btn btn-success btn-reservar" reservar-horario="<%=start_t%>" reservar-data="<%= date %>" title="<%= "#{start_t}_#{date}" %>" data-toggle="modal" data-target="#reservaModal">Reservar</button>
              </td>
          <% end %>
        <% end %>
      </tr>
      <% start_t=start_t+2 %>
      <% end_t=end_t+2 %>
      <% i=i+1 %>
    <% end %>

    </tbody>
  </table>
</div>
<br>
<%= link_to 'Voltar', rooms_path, class: 'btn btn-secondary' %>

<!-- Modal para reservar sala -->
<div class="modal fade" id="reservaModal" tabindex="-1" role="dialog" aria-labelledby="reservaModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reservaModalLabel">Reservar sala - <%=@room.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with url: appointments_path(@room), :html => {class: "form-horizontal", role: "form"} do |form| %>
        <div class="modal-body">
          <div class="form-row">
            <div class="form-group col-md-6">
              <label>Dia do aluguel</label>
              <%= form.date_field :appointment_date_disabled, class: 'form-control appointment-date-form' , :disabled => true  %>
            </div>
            <div class="form-group col-md-6">
              <label>Horário</label>
              <%= form.hidden_field :appointment_date, class: "appointment-date-form" %>
              <%= form.hidden_field :start_time, class: "appointment-time-form" %>
              <%= form.select :start_time_disabled, options_for_select([['6:00 - 8:00', "6:00"], ['8:00 - 10:00', "8:00"], ['10:00 - 12:00', "10:00"],
                                                              ['12:00 - 14:00', "12:00"], ['14:00 - 16:00', "14:00"], ['16:00 - 18:00', "16:00"], ['18:00 - 20:00', "18:00"], ['20:00 - 22:00', "20:00"],
                                                              ['22:00 - 24:00', "22:00"]]),
                              {}, class: "form-control appointment-time-form", :disabled => true %>
            </div >
      
            <div class="form-group col-md-12">
                <label> Descrição </label>
                <%= form.text_area :description, rows: 3, class:"form-control" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <%= form.submit "Reservar", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {
        $(".btn-reservar").click(function() {
            $(".appointment-date-form").val($(this).attr("reservar-data"));
            $(".appointment-time-form").val($(this).attr("reservar-horario") + ":00");
        });
    });
</script>

app/views/appointments/status.js.erb
var id = "<%= @appointment.id %>"
var status = "<%= Appointment.status_names[@appointment.status] %>"
$('#status' + id).text(status);

app/views/appointments/weeks_appointments.html.erb
<table class="table" id="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Username</th>
    <th scope="col">Sala</th>
    <th scope="col">Appointment Date</th>
    <th scope="col">Start Time</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @weeks_appointments.each do |appointment| %>
    <tr>
      <th scope="row">1</th>
      <td class="appointment-data"> <%= appointment.user.username %> </td>
      <td class="appointment-data"> <%= appointment.room.name %> </td>
      <td class="appointment-data"> <%= appointment.appointment_date %> </td>
      <td class="appointment-data"> <%= appointment.start_time %> </td>
      <td> <%= link_to 'Editar', edit_appointment_path(appointment.id) %> </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Voltar ao perfil", root_path, class:'btn btn-secondary' %>