config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'

  get '/pending_appointments', to: 'appointments#pending_appointments'
  get '/accepted_appointments', to: 'appointments#accepted_appointments'


  root 'home#index'

  devise_for :users, skip: [:registrations, :sessions], :controllers => { :registrations => "users/registrations" }

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :"new_user_session"
    post 'login', to: 'users/sessions#create', as: :"user_session"
    delete 'logout', to: 'users/sessions#destroy', as: :"destroy_user_session"
    get 'create_user', to: 'users/registrations#new', as: :"new_user_registration"
    post 'create_user', to: 'users/registrations#create', as: :"user_registration"
    post 'create_user_as_admin', to: 'users/registrations#create_as_admin', as: :"admin_registration"
    delete '', to: 'users/registrations#destroy', as: :""
    patch 'users/:id', to: 'users/registrations#update', as: :"update_user_registration"
    put 'users/:id', to: 'users/registrations#update', as: :""
    get 'users/:id/edit', to: 'users/registrations#edit', as: :"edit_user_registration"

  end

  resources :rooms
  resources :appointments
  get 'my-appointments' => 'appointments#my_appointments'
  get 'all-appointments' => 'appointments#all_appointments'
  get 'backoffice', to: 'backoffice/dashboard#index'
  get 'signup_user', to: 'backoffice/dashboard#signup_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header-admin.html.erb
<div class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <%= link_to 'Reserva de Salas - Backoffice', backoffice_path, class: 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Salas">
          <%= link_to rooms_path, class: 'nav-link' do %>
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">Salas Existentes</span>
          <% end %>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
          <%= link_to my_appointments_path(@user), class: 'nav-link' do %>
            <i class="fa fa-fw fa-calendar"></i>
            <span class="nav-link-text">Meus aluguéis</span>
          <% end %>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <%= link_to new_room_path, class: 'nav-link' do %>
            <i class="fa fa-fw fa-plus-circle"></i>
            <span class="nav-link-text">Criar Salas</span>
          <% end %>
        </li>
        <% if current_user.is_admin %>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
            <%= link_to all_appointments_path, class: 'nav-link' do %>
              <i class="fa fa-fw fa-eye"></i>
              <span class="nav-link-text">Todos aluguéis</span>
            <% end %>
          </li>

          <li class="nav-item">
              <%= link_to users_show_path, class: 'nav-link' do%>
                <i class="fa fa-fw fa-eye"></i>
                Todos os usuários
              <% end %>
          </li>
        <%end%>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fa fa-angle-up"></i>
  </a>
</div>
<%= javascript_include_tag "header"%>

app/views/layouts/_header-user.html.erb
<div class="fixed-nav sticky-footer bg-dark" id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <%= link_to 'Reserva de Salas', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Salas">
        <%= link_to rooms_path, class: 'nav-link' do %>
          <i class="fa fa-fw fa-list"></i>
          <span class="nav-link-text">Salas Existentes</span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Buscar-Salas-Livres">
        <%= link_to search_rooms_path, class: 'nav-link' do %>
          <i class="fa fa-fw fa-search"></i>
          <span class="nav-link-text">Buscar Salas Livres</span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <%= link_to my_appointments_path(@user), class: 'nav-link' do %>
          <i class="fa fa-fw fa-calendar"></i>
          <span class="nav-link-text">Meus aluguéis</span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
        <%= link_to edit_user_registration_path(current_user.id), class: 'nav-link' do %>
          <i class="fa fa-fw fa-edit"></i>
          <span class="nav-link-text">Editar perfil</span>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
          <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        <% end %>
      </li>
    </ul>
  </div>
</nav>
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fa fa-angle-up"></i>
</a>
</div>
<%= javascript_include_tag "header"%>

app/views/layouts/_login-form.html.erb
<div>
  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name), class: 'login100-form validate-form', name: 'pass' ) do |f| %>
					<span class="login100-form-title p-b-55">
						<h2 style="font-weight: bold;">
              Log in
            </h2>
					</span>

          <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'input100', placeholder: 'Email' %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-envelope"></span>
						</span>
          </div>

          <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
            <%= f.password_field :password, autocomplete: "off", class: 'input100', placeholder: "Senha" %>
            <%= link_to '(Esqueceu sua senha ?)', new_password_reset_path %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-lock"></span>
						</span>
          </div>

          <div class="contact100-form-checkbox m-l-4">
            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <%= f.check_box :remember_me, class: 'input-checkbox100', id: 'ckb1' %>
                <%= f.label "Lembre-se de mim", class: 'label-checkbox100', for: 'ckb1' %>
              </div>
            <% end -%>
          </div>

          <div class="container-login100-form-btn p-t-25">
            <%= f.submit "Log in", class: 'login100-form-btn' %>
          </div>

          <div class="text-center w-full p-t-115">
						<span class="txt1">
							Não é cadastrado ainda?
						</span>

            <%= link_to 'Cadastre-se agora!', new_user_registration_path, class: 'txt1 bo1 hov1' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_password_reset-form.html.erb
<div>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
      <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
                  <span class="login100-form-title p-b-55">
                      <h2 style="font-weight: bold;">
            Recuperação de senha
          </h2>
                  </span>
        
        <div class="wrap-input100 validate-input m-b-16" >
        <%= hidden_field_tag :email, @user.email %>
            <span class="focus-input100"></span>
        </div>
        
        <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
          <%= f.password_field :password, class: 'input100', placeholder: 'Nova Senha' %>
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Password Confirmation is required">
          <%= f.password_field :password_confirmation, class: 'input100', placeholder: 'Confirmação' %>
          <span class="focus-input100"></span>
        </div>        

        <div class="container-login100-form-btn p-t-25">
          <%= f.submit "Alterar Senha", class: 'login100-form-btn' %>
        </div>

        <div class="text-center w-full p-t-115">
                      
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/_password_reset_email-form.erb
<div>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
      <%= form_for(:password_reset, url: password_resets_path) do |f| %>
                  <span class="login100-form-title p-b-55">
                      <h2 style="font-weight: bold;">
            Recuperação de senha
          </h2>
                  </span>

        <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'input100', placeholder: 'Email' %>
          <span class="focus-input100"></span>
          <span class="symbol-input100">
                          <span class="fa fa-envelope"></span>
                      </span>
        </div>

        <div class="container-login100-form-btn p-t-25">
          <%= f.submit "Enviar", class: 'login100-form-btn' %>
        </div>

        <div class="text-center w-full p-t-115">
                      <span class="txt1">
                          Não é cadastrado ainda?
                      </span>

          <%= link_to 'Cadastre-se agora!', new_user_registration_path, class: 'txt1 bo1 hov1' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/_register-form.html.erb
<div>
  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
        <%= form_for(:user ,:html => {class: "form-horizontal ogin100-form validate-form", role: "form"}, url: user_registration_path, method: :post) do |f| %>
					<%= devise_error_messages! %>
          <span class="login100-form-title p-b-55">
						<h2 style="font-weight: bold;">
              Sign up
            </h2>
					</span>

          <div class="wrap-input100 validate-input m-b-16">
            <%= f.text_field :username, autofocus: true, autocomplete: "off", class: 'input100', placeholder: 'Nome de usuário' %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-user"></span>
						</span>
          </div>

          <div class="wrap-input100 validate-input m-b-16">
            <%= f.text_field :registration, autofocus: true, autocomplete: "off", class: 'input100', placeholder: 'Matrícula' %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-address-card"></span>
						</span>
          </div>

          <div class="wrap-input100 validate-input m-b-16">
            <%= f.text_field :course, autofocus: true, autocomplete: "off", class: 'input100', placeholder: 'Curso' %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-university"></span>
						</span>
          </div>

          <div class="wrap-input100 validate-input m-b-16" data-validate = "Valid email is required: ex@abc.xyz">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'input100', placeholder: 'Email' %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-envelope"></span>
						</span>
          </div>

          <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
            <%= f.password_field :password, autocomplete: "off", class: 'input100', placeholder: "Senha" %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-lock"></span>
						</span>
          </div>

          <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
            <%= f.password_field :password_confirmation, autocomplete: "off", class: 'input100', placeholder: "Confirmar senha" %>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
							<span class="fa fa-lock"></span>
						</span>
          </div>

          <div class="container-login100-form-btn p-t-25">
            <%= f.submit "Sign up", class: 'login100-form-btn' %>
          </div>

          <div class="text-center w-full p-t-115">
						<span class="txt1">
							Já é cadastrado?
						</span>

            <%= link_to 'Entre aqui!', new_user_session_path, class: 'txt1 bo1 hov1' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservaDeSalas</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "salas" %>
    <%= yield(:css) %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <% flash.each do |key, message| %>
      <% if key == 'notice' %>
        <% key = 'success' %>
      <% end %>
      <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if user_signed_in? == true %>
      <% if current_user.is_admin? == true %>
        <%= render 'layouts/header-admin' %>
        <div class="content-wrapper">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      <% else %>
        <%= render 'layouts/header-user' %>
        <div class="content-wrapper">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= yield %>
    <% end %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backoffice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header-admin'%>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
        <%= render 'layouts/header-user' %>
        <%= yield %>
    <% end %>
    <% if !user_signed_in? %>
        <%= yield %>
    <% end %>
  </body>
</html>